{
 "title": "pgSCV: Pgbouncer",
 "description": "Pgbouncer dashboard for pgSCV metrics (Prometheus version, pgSCV 0.8.4 edition)",
 "tags": [ "pgSCV" ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pgscv_services_registered_total{service=\"pgbouncer\"},instance)"
    }
   },
   {
    "name": "pgbouncer",
    "label": "Pgbouncer",
    "query": {
     "query": "label_values(pgscv_services_registered_total{instance=\"$instance\", service=\"pgbouncer\"},service_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Current status of Pgbouncer service.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_up{service_id=\"$pgbouncer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "description": "Total number of client connections established.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_client_connections_in_flight{instance=\"$instance\",service_id=\"$pgbouncer\",database!=\"pgbouncer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server connections",
   "type": "stat",
   "description": "Total number of server connections established.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_pool_connections_in_flight{instance=\"$instance\",service_id=\"$pgbouncer\",database!=\"pgbouncer\",state=~\"sv_.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Pgbouncer version.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgbouncer_version{instance=\"$instance\",service_id=\"$pgbouncer\"}) by (version)"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pools utilization",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum by (database,user) (max_over_time(pgbouncer_pool_connections_in_flight{instance=\"$instance\",service_id=\"$pgbouncer\",state=~\"sv_.+\",database!=\"pgbouncer\"}[1m]))/ on() group_left() (max(pgbouncer_service_database_pool_size{instance=\"$instance\",service_id=\"$pgbouncer\",database!=\"pgbouncer\"} or pgbouncer_service_settings_info{name=\"default_pool_size\"}))",
       "legendFormat": "{{ database }}/{{ user }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, sum by (address) (max_over_time(pgbouncer_client_connections_in_flight{instance=\"$instance\",service_id=\"$pgbouncer\",database!=\"pgbouncer\"}[1m])))",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "Server connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state) (max_over_time(pgbouncer_pool_connections_in_flight{instance=\"$instance\",service_id=\"$pgbouncer\",database!=\"pgbouncer\",state=~\"sv_.+\"}[1m]))",
       "legendFormat": "{{ state }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Waiting clients",
     "type": "timeseries",
     "description": "Client connections have sent queries but have not yet got a server connection.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, sum by (user) (max_over_time(pgbouncer_pool_connections_in_flight{instance=\"$instance\",service_id=\"$pgbouncer\",state=\"cl_waiting\"}[1m])))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Waiting time",
     "type": "timeseries",
     "description": "Total number of time spent by pgbouncer when connected to PostgreSQL executing queries or processing transactions per database.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum by(database) (rate(pgbouncer_spent_seconds_total{instance=\"$instance\",service_id=\"$pgbouncer\",type=\"waiting\"}[1m])))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Transactions, per second",
     "type": "timeseries",
     "description": "Transactions processed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, sum by (database) (rate(pgbouncer_transactions_total{instance=\"$instance\",service_id=\"$pgbouncer\"}[1m])))",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Transactions duration, avg",
     "type": "timeseries",
     "description": "Average duration of processed transactions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum by(database) (rate(pgbouncer_spent_seconds_total{instance=\"$instance\",service_id=\"$pgbouncer\",mode=\"xact\"}[1m])) / sum by (database) (rate(pgbouncer_transactions_total{instance=\"$instance\",service_id=\"$pgbouncer\"}[1m])))",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Queries, per second",
     "type": "timeseries",
     "description": "Queries processed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, sum by (database) (rate(pgbouncer_queries_total{instance=\"$instance\",service_id=\"$pgbouncer\"}[1m])))",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Queries duration, avg",
     "type": "timeseries",
     "description": "Average duration of processed queries.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum by(database) (rate(pgbouncer_spent_seconds_total{instance=\"$instance\",service_id=\"$pgbouncer\",mode=\"query\"}[1m])) / sum by (database) (rate(pgbouncer_queries_total{instance=\"$instance\",service_id=\"$pgbouncer\"}[1m])))",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(type) (rate(pgbouncer_bytes_total{instance=\"$instance\",service_id=\"$pgbouncer\",database!=\"pgbouncer\"}[1m]))",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pgbouncer settings",
     "type": "table",
     "description": "Pgbouncer settings.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (pgbouncer_service_settings_info{instance=\"$instance\",service_id=\"$pgbouncer\"})"
      }
     ]
    }
   ]
  }
 ]
}