before:
  hooks:
    - make dep

builds:
  - binary: pgscv
    main: ./cmd
    goarch:
      - '386'
      - amd64
      - arm64
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -a -installsuffix cgo
      - -X main.appName=pgscv -X main.gitTag={{.Tag}} -X main.gitCommit={{.Commit}} -X main.gitBranch={{.Branch}}

archives:
  - builds: [pgscv]
    builds_info:
      group: root
      owner: root
    wrap_in_directory: false
    files:
      - LICENSE
      - src: "deploy/pgscv.yaml"
        strip_parent: true
        info:
          owner: root
          group: root
          mode: 0640
      - src: "deploy/pgscv.service"
        strip_parent: true
        info:
          owner: root
          group: root
          mode: 0644
      - src: "deploy/pgscv.default"
        strip_parent: true
        info:
          owner: root
          group: root
          mode: 0644
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

changelog:
  sort: asc

checksum:
  name_template: 'checksums.txt'

nfpms:
  - vendor: pgscv
    homepage: https://github.com/cherts/pgscv
    maintainer: Mikhail Grigorev
    description: pgSCV - PostgreSQL ecosystem metrics collector.
    license: BSD-3
    formats: []
    bindir: /usr/sbin
