apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgscv.fullname" . }}-pgscv
  labels:
    link-app: pgscv
  {{- include "pgscv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgscv.type }}
  selector:
    link-app: pgscv
  {{- include "pgscv.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.pgscv.ports | toYaml | nindent 2 -}}