{
 "title": "pgSCV: System",
 "description": "System dashboard for pgSCV metrics (Prometheus version, pgSCV v0.9.7 edition)",
 "tags": [ "pgSCV" ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": {
     "query": "label_values(node_filesystem_bytes_total, mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Current CPU usage.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum (rate(node_cpu_seconds_total{instance=\"$instance\",mode!=\"idle\"}[1m])) / on (instance) group_left sum(rate(node_cpu_seconds_all_total{instance=\"$instance\",}[1m]))"
    }
   ]
  },
  {
   "title": "Storage latency",
   "type": "stat",
   "description": "Current latency of IO operations.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_time_seconds_total{instance=\"$instance\"}[1m])) / (sum (rate(node_disk_completed_total{instance=\"$instance\"}[1m])) + on() group_left vector(1))"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "stat",
   "description": "Rate of network errors (per minute) across all interfaces.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_events_total{instance=\"$instance\",device!~\"veth.+\",event=~\"errs|fifo|frame|drop\"}[1m]))"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "stat",
   "description": "Amount of available memory (including cached and buffers).",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree{instance=\"$instance\"} + node_memory_Cached{instance=\"$instance\"} + node_memory_Buffers{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "table",
   "description": "Max disk space usage across all filesystems.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 * (sum by (mountpoint) (node_filesystem_bytes{instance=\"$instance\",usage=~\"used|reserved\"}) / (sum by (mountpoint) (node_filesystem_bytes_total{instance=\"$instance\"})))",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU, Storage Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage, %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum by (mode) (rate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\"}[1m])) / on (instance) group_left sum(rate(node_cpu_seconds_all_total{instance=\"$instance\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage utilization, %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (device) (rate(node_disk_io_time_seconds_total{instance=\"$instance\"}[1m])) / on() group_left() rate(node_uptime_up_seconds_total{instance=\"$instance\"}[1m]) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory and Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(node_memory_MemFree{instance=\"$instance\"}[1m])",
       "legendFormat": "free"
      },
      {
       "expr": "avg_over_time(node_memory_Buffers{instance=\"$instance\"}[1m])",
       "legendFormat": "buffers"
      },
      {
       "expr": "avg_over_time(node_memory_Cached{instance=\"$instance\"}[1m])",
       "legendFormat": "cached"
      },
      {
       "expr": "avg_over_time(node_memory_MemUsed{instance=\"$instance\"}[1m])",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Swap usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg_over_time(node_memory_SwapFree{instance=\"$instance\"}[1m])",
       "legendFormat": "free"
      },
      {
       "expr": "avg_over_time(node_memory_SwapUsed{instance=\"$instance\"}[1m])",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Swap IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin{instance=\"$instance\"}[1m])*4096",
       "legendFormat": "in"
      },
      {
       "expr": "rate(node_vmstat_pswpout{instance=\"$instance\"}[1m])*4096",
       "legendFormat": "out"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Storage latency, ms",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (device) (rate(node_disk_time_seconds_total{instance=\"$instance\"}[1m])) / (sum by (device) (rate(node_disk_completed_total{instance=\"$instance\"}[1m])) + on() group_left vector(1))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Read, bytes per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_disk_bytes_total{instance=\"$instance\",type=\"read\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Write, bytes per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_disk_bytes_total{instance=\"$instance\",type=\"write\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Read operations, per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_completed_total{instance=\"$instance\",type=\"read\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Write operations, per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_completed_total{instance=\"$instance\",type=\"write\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Discard operations, per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_completed_total{instance=\"$instance\",type=\"discard\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Flush operations, per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_completed_total{instance=\"$instance\",type=\"flush\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$mountpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "repeat": "mountpoint",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_bytes{instance=\"$instance\",usage=~\"used|reserved|avail\",mountpoint=\"$mountpoint\"}",
       "legendFormat": "{{ usage }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Received, bytes per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_network_bytes_total{instance=\"$instance\",device!~\"veth.+\",type=\"recv\"}[1m])",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Sent, bytes per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_network_bytes_total{instance=\"$instance\",device!~\"veth.+\",type=\"sent\"}[1m])",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Received, packets per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_packets_total{instance=\"$instance\",device!~\"veth.+\",type=\"recv\"}[1m])",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Sent, packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_packets_total{instance=\"$instance\",device!~\"veth.+\",type=\"sent\"}[1m])",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Errors, per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (device, type) (increase(node_network_events_total{instance=\"$instance\",device!~\"veth.+\",event=~\"errs|fifo|frame\"}[1m]))",
       "legendFormat": "{{ device }}/{{ type }}"
      }
     ]
    },
    {
     "title": "Dropped, packets per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (device, type) (increase(node_network_events_total{instance=\"$instance\",device!~\"veth.+\",event=\"drop\"}[1m]))",
       "legendFormat": "{{ device }}/{{ type }}"
      }
     ]
    }
   ]
  }
 ]
}