listen_address: 127.0.0.1:9890
#authentication:
#  username: monitoring
#  password: supersecretpassword
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#no_track_mode: false
#collect_top_query: 10
#collect_top_table: 10
#collect_top_index: 10
#skip_conn_error_mode: false
#url_prefix: "example.com"
#conn_timeout: 3
#throttling_interval: 25
#discovery:
#  yandex_mdb:
#    type: yandex-mdb
#    config:
#      - authorized_key: /path/to/secret/authorized_key.json
#        folder_id: "b1000000000000"
#        password: "password"
#        password_from_env: DB_PASSWORD
#        user: "postgres_exporter"
#        refresh_interval: 5
#        clusters:
#          - name: ".*"
#            db:
#            exclude_name:
#            exclude_db:
services:
  "postgres:5432":
    service_type: "postgres"
    conninfo: "postgres://postgres:password@127.0.0.1:5432/postgres"
  "pgbouncer:6432": 
    service_type: "pgbouncer"
    conninfo: "postgres://pgbouncer:password@127.0.0.1:6432/pgbouncer"
#  "patroni1":
#    service_type: "patroni"
#    baseurl: "http://127.0.0.1:8008"
#  "patroni2":
#    service_type: "patroni"
#    baseurl: "http://127.0.0.1:8009"
#  "patroni3":
#    service_type: "patroni"
#    baseurl: "http://127.0.0.1:8010"
#databases: "^([a-zA-Z0-9])+_(prod|PROD)$"
#disable_collectors:
#  - system
#  - system/pgscv
#  - system/loadaverage
#  - system/cpu
#  - system/diskstats
#  - system/filesystems
#  - system/netdev
#  - system/network
#  - system/memory
#  - system/sysconfig
#  - system/sysinfo
#  - postgres/pgscv
#  - postgres/activity
#  - postgres/archiver
#  - postgres/bgwriter
#  - postgres/conflicts
#  - postgres/databases
#  - postgres/indexes
#  - postgres/functions
#  - postgres/locks
#  - postgres/logs
#  - postgres/replication
#  - postgres/replication_slots
#  - postgres/statements
#  - postgres/schemas
#  - postgres/settings
#  - postgres/storage
#  - postgres/tables
#  - postgres/wal
#  - postgres/custom
#  - pgbouncer/pgscv
#  - pgbouncer/pools
#  - pgbouncer/stats
#  - pgbouncer/settings
#  - patroni/pgscv
#  - patroni/common
#collectors:
#  postgres/custom:
#    filters:
#      schemaname:
#        exclude: "^.+_(uat|dev|stage|UAT|DEV|STAGE)$"
#    subsystems:
#      table:
#        databases: "test[0-9]+|pgbench"
#        query: "select schemaname,relname,seq_scan,n_tup_ins,n_tup_upd,n_tup_del from pg_stat_user_tables"
#        metrics:
#          - name: seq_scans
#            usage: COUNTER
#            value: seq_scan
#            labels:
#              - schemaname
#              - relname
#            description: "Total number of tuples by operation."
#          - name: tuples_totals
#            usage: COUNTER
#            labeled_values:
#              tuples: [ n_tup_ins, n_tup_upd, n_tup_del ]
#            labels:
#              - schemaname
#              - relname
#            description: "Total number of tuples by operation."
