apiVersion: 1

datasources:
  - name: victoriametrics
    type: prometheus
    access: proxy
    orgId: 1
    uid: DS_VM_01
    url: http://victoriametrics:8428
    basicAuth: false
    isDefault: true
    editable: true
