{
 "title": "pgSCV: PostgreSQL",
 "description": "PostgreSQL dashboard for pgSCV metrics (Prometheus version, pgSCV 0.9.2 edition)",
 "tags": [ "pgSCV" ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pgscv_services_registered_total{service=\"postgres\"},instance)"
    }
   },
   {
    "name": "postgres",
    "label": "PostgreSQL",
    "query": {
     "query": "label_values(pgscv_services_registered_total{instance=\"$instance\", service=\"postgres\"},service_id)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(postgres_database_size_bytes{instance=\"$instance\"},database)"
    }
   },
   { "name": "exclude", "label": "Exclude", "query": "postgres,pgscv" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service status",
   "type": "stat",
   "description": "Current status of PostgreSQL service.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_up{instance=\"$instance\",service_id=\"$postgres\"}",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Current role of PostgreSQL node (Primary or Replica).",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_recovery_info{instance=\"$instance\",service_id=\"$postgres\"}",
     "legendFormat": "statements"
    }
   ]
  },
  {
   "title": "Statements",
   "type": "stat",
   "description": "Rate of successfully executed statements per second.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\",user!~\"^$exclude$\"}[1m]))",
     "legendFormat": "statements"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of log messages rate (per minute) with severity higher than LOG (e.g. WARNING, ERROR, FATAL and PANIC).",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_log_messages_total{level!=\"log\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Response time, avg",
   "type": "stat",
   "description": "Average response time calculated using time of executed statements.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_statements_time_seconds_all_total{instance=\"$instance\",service_id=\"$postgres\",user!~\"^$exclude$\"}[1m])) / sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\",user!~\"^$exclude$\"}[1m]))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Longest activity",
   "type": "stat",
   "description": "Current longest transaction activity, initiated by clients or background service (e.g. autovacuum).",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\",user!~\"^$exclude$\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "stat",
   "description": "Total number of connected clients.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\",user!~\"^$exclude$\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Invalid indexes",
   "type": "stat",
   "description": "Total number of invalid indexed in cluster. See Tables panel for more detail.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(postgres_index_scans_total{instance=\"$instance\",service_id=\"$postgres\",isvalid=\"false\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Inactive replication slots",
   "type": "stat",
   "description": "Total number of inactive replication slots.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(postgres_replication_slot_wal_retain_bytes{instance=\"$instance\",service_id=\"$postgres\",active=\"false\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Rollbacks",
   "type": "stat",
   "description": "Total number of rollbacks. See \"Client activity\" dashboard for more detail. Select primary node.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postgres_database_xact_rollbacks_total{instance=\"$instance\",service_id=\"$postgres\",database!~\"^$exclude$\",user!~\"^$exclude$\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "stat",
   "description": "Total number of conflicts per minute. See the documentation for the pg_stat_database view for more details.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postgres_database_conflicts_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "description": "Total number of deadlocks occurred. See \"Deadlocks, per minute\" dashboard for more detail.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postgres_database_deadlocks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Checksum failures",
   "type": "stat",
   "description": "Total number of checksum failures occurred per minute.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postgres_database_checksum_failures_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Session failures",
   "type": "stat",
   "description": "Total number of sessions established to this database and closed by reason abandoned, fatal or killed. See \"Session activity\" dashboard for more detail.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postgres_database_sessions_total{instance=\"$instance\",service_id=\"$postgres\",reason=~\"abandoned|fatal|killed\",database!~\"^$exclude$\"}[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client activity",
     "type": "timeseries",
     "description": "Query activity produced by connected clients.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m]))",
       "legendFormat": "statements"
      },
      {
       "expr": "sum(rate(postgres_database_xact_commits_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m]))",
       "legendFormat": "commits"
      },
      {
       "expr": "sum(rate(postgres_database_xact_rollbacks_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m]))",
       "legendFormat": "rollbacks"
      }
     ]
    },
    {
     "title": "Longest activity",
     "type": "timeseries",
     "description": "The most longest activity produced by connected clients and background services.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, max by (user) (postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}))",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "Client connections",
     "type": "timeseries",
     "description": "States of connections established by clients (doesn't include states of background services).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state) (postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Client connections (without idle)",
     "type": "timeseries",
     "description": "States of connections by database/user/state (without idle* state and autovacuum)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\",state!~\"^(idle|idlexact)\",database=~\"$database\",user!~\"^(autovacuum|worker).*\",user!~\"^$exclude$\"}",
       "legendFormat": "{{database}}/{{user}}/{{state}}"
      }
     ]
    },
    {
     "title": "Session activity",
     "type": "timeseries",
     "description": "Total number of sessions established to this database and closed by each reason. See the documentation for the pg_stat_database view for more details. Require PostgreSQL v14+",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (database,reason) (increase(postgres_database_sessions_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m]))",
       "legendFormat": "{{database}}/{{reason}}"
      },
      {
       "expr": "sum by (database) (increase(postgres_database_sessions_all_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m]))",
       "legendFormat": "{{database}}/TOTAL"
      },
      {
       "expr": "sum by (service_id) (increase(postgres_database_sessions_all_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m]))",
       "legendFormat": "TOTAL"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Log messages, per minute",
     "type": "timeseries",
     "description": "Messages written to log, by severity.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (level) (increase(postgres_log_messages_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Log directory, bytes",
     "type": "timeseries",
     "description": "Total size of log directory in bytes.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_log_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logging settings",
     "type": "table",
     "description": "Important: when logging_collector is disabled, log metrics will not be collected.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"logging_collector|log_directory|log_filename\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements (pg_stat_statements required)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Calls",
     "type": "timeseries",
     "description": "The top-most executed statements.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "timeseries",
     "description": "The top-most statements by returned rows.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_rows_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Total time",
     "type": "timeseries",
     "description": "The top-most statements by total time (planning, executing and doing IO).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_time_seconds_all_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "IO time",
     "type": "timeseries",
     "description": "The top-most statements by IO time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum without (mode) (rate(postgres_statements_time_seconds_total{mode=~\"ioread|iowrite\",instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\",user!~\"^$exclude$\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks and wait events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Wait events, by type",
     "type": "timeseries",
     "description": "Wait events aggregated by type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type) (postgres_activity_wait_events_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Wait events",
     "type": "timeseries",
     "description": "The top-most wait events occurred.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, postgres_activity_wait_events_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ type }}:{{ event }}"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "timeseries",
     "description": "Total number of locks acquired.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres_locks_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Deadlocks, per minute",
     "type": "timeseries",
     "description": "Total number of deadlocks per minute.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(postgres_database_deadlocks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "deadlocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replication lag, bytes",
     "type": "timeseries",
     "description": "Total amount of replication lag, when standbys left behind the master.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (client_addr) (postgres_replication_lag_all_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ client_addr }}"
      }
     ]
    },
    {
     "title": "Replication lag, seconds",
     "type": "timeseries",
     "description": "Total amount of replication lag, when standbys left behind the master.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (client_addr) (postgres_replication_lag_all_seconds{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ client_addr }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAL write, bytes per second",
     "type": "timeseries",
     "description": "Amount of WAL generated or received by Postgres instance.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(postgres_wal_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "WAL"
      }
     ]
    },
    {
     "title": "WAL directory size",
     "type": "timeseries",
     "description": "Total size of WAL directory, in bytes.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_wal_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "WAL settings",
     "type": "table",
     "description": "WAL settings",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"(max|min)_wal_size|max_slot_wal_keep_size|full_page_writes|wal_keep_(size|segments)|wal_(compression|level|log_hints)\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Vacuum maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Vacuums",
     "type": "timeseries",
     "description": "Total number of automatic and user-initiated vacuum operations.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres_activity_vacuums_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Vacuumed tables, per-minute",
     "type": "timeseries",
     "description": "The top-most vacuumed tables.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, increase(postgres_table_maintenance_total{type=\"autovacuum\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Autovacuum settings",
     "type": "table",
     "description": "Autovacuum settings.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"^(auto)?vacuum.+\"})"
      }
     ]
    },
    {
     "title": "Transactions left before wraparound",
     "type": "timeseries",
     "description": "Total number transactions left before XID wraparound occurs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres_xacts_left_before_wraparound{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ xid_from }}"
      }
     ]
    },
    {
     "title": "Sufficiency of autovacuum workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres_activity_vacuums_in_flight{instance=\"$instance\",service_id=\"$postgres\"}/on(service_id, instance) group_left() postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\", name=\"autovacuum_max_workers\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Checkpoints",
     "type": "timeseries",
     "description": "Total number of checkpoints occurred.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(postgres_checkpoints_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{ checkpoint }}"
      }
     ]
    },
    {
     "title": "Background writes",
     "type": "timeseries",
     "description": "Total writes performed by background services or by backends implicitly.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(postgres_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{ process }}"
      },
      {
       "expr": "rate(postgres_wal_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "wal"
      },
      {
       "expr": "sum(rate(postgres_database_temp_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "tempfiles"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk space usage",
     "type": "timeseries",
     "description": "Disk space usage by Postgres instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_tablespace_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ tablespace }}"
      },
      {
       "expr": "postgres_wal_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "wal"
      },
      {
       "expr": "postgres_log_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "log"
      }
     ]
    },
    {
     "title": "Databases",
     "type": "timeseries",
     "description": "Top databases by size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5, postgres_database_size_bytes{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"})",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "timeseries",
     "description": "Top tables by size in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5, postgres_table_size_bytes{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"})",
       "legendFormat": "{{ database }}/{{ schema }}.{{ table }}"
      }
     ]
    },
    {
     "title": "Indexes",
     "type": "timeseries",
     "description": "Top indexes by size in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5, postgres_index_size_bytes{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"})",
       "legendFormat": "{{ database }}/{{ schema }}.{{ table }}.{{ index }}"
      }
     ]
    },
    {
     "title": "Databases temporary files",
     "type": "timeseries",
     "description": "Top databases by produced temporary files in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5, increase(postgres_database_temp_bytes_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"}[1m]))",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Temporary files in-flight",
     "type": "timeseries",
     "description": "Total size of active temporary files in-flight.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_temp_bytes_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ tablespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sequential read, by rows",
     "type": "timeseries",
     "description": "The top-most tables which accessed sequentially.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_seq_tup_read_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"}[1m]))",
       "legendFormat": "{{database}}/{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "INSERTs",
     "type": "timeseries",
     "description": "The top-most tables with performed INSERTs per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_inserted_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"}[1m]))",
       "legendFormat": "{{database}}/{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Sequential scans/min",
     "type": "timeseries",
     "description": "Top-most tables with performed sequential scans  per minute.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_seq_scan_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"}[1m]))",
       "legendFormat": "{{database}}/{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "UPDATEs",
     "type": "timeseries",
     "description": "The top-most tables with performed UPDATEs (including HOT) per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_updated_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"}[1m]))",
       "legendFormat": "{{database}}/{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Dead tuples",
     "type": "timeseries",
     "description": "The top-most tables with dead tuples.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, postgres_table_tuples_dead_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"})",
       "legendFormat": "{{database}}/{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "DELETEs",
     "type": "timeseries",
     "description": "The top-most tables with performed DELETEs per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_deleted_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"}[1m]))",
       "legendFormat": "{{database}}/{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "timeseries",
     "description": "The top-10 most-table in number of rows based on pg_class.reltuples value.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, postgres_table_tuples_total{instance=\"$instance\",service_id=\"$postgres\",database=~\"$database\"})",
       "legendFormat": "{{database}}/{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Invalid indexes",
     "type": "table",
     "description": "List of invalid indexes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (database, schema, table, index) (postgres_index_scans_total{instance=\"$instance\",service_id=\"$postgres\",isvalid=\"false\",database=~\"$database\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL archiving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAL archiving lag, bytes",
     "type": "timeseries",
     "description": "Total amount of WAL segments (in bytes) which are not archived yet.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_archiver_lag_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "WAL archiving, per minute",
     "type": "timeseries",
     "description": "Total amount of WAL segments processed per minute.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(postgres_archiver_archived_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "archived"
      },
      {
       "expr": "increase(postgres_archiver_failed_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "WAL archiving settings",
     "type": "table",
     "description": "Important: when WAL archiving is disabled, metrics will not be collected.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"archive_.+\"})"
      }
     ]
    }
   ]
  }
 ]
}