services:
  pgbouncer9:
    container_name: pgbouncer9
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer9
    volumes:
      - ${PWD}/pgbouncer/conf9:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6429:5432"
    depends_on:
      postgres9:
        condition: service_healthy
  pgbouncer10:
    container_name: pgbouncer10
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer10
    volumes:
      - ${PWD}/pgbouncer/conf10:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6430:5432"
    depends_on:
      postgres10:
        condition: service_healthy
  pgbouncer11:
    container_name: pgbouncer11
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer11
    volumes:
      - ${PWD}/pgbouncer/conf11:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6431:5432"
    depends_on:
      postgres11:
        condition: service_healthy
  pgbouncer12:
    container_name: pgbouncer12
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer12
    volumes:
      - ${PWD}/pgbouncer/conf12:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6432:5432"
    depends_on:
      postgres12:
        condition: service_healthy
  pgbouncer13:
    container_name: pgbouncer13
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer13
    volumes:
      - ${PWD}/pgbouncer/conf13:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6433:5432"
    depends_on:
      postgres13:
        condition: service_healthy
  pgbouncer14:
    container_name: pgbouncer14
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer14
    volumes:
      - ${PWD}/pgbouncer/conf14:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6434:5432"
    depends_on:
      - postgres14
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost']
  pgbouncer15:
    container_name: pgbouncer15
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer15
    volumes:
      - ${PWD}/pgbouncer/conf15:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6435:5432"
    depends_on:
      postgres15:
        condition: service_healthy
  pgbouncer16:
    container_name: pgbouncer16
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer16
    volumes:
      - ${PWD}/pgbouncer/conf16:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6436:5432"
    depends_on:
      postgres16:
        condition: service_healthy
  pgbouncer17:
    container_name: pgbouncer17
    image: edoburu/pgbouncer:latest
    hostname: pgbouncer17
    volumes:
      - ${PWD}/pgbouncer/conf17:/etc/pgbouncer
    networks: [ monitoring ]
    ports:
      - "6437:5432"
    depends_on:
      postgres17:
        condition: service_healthy

networks:
  monitoring:
