---
- hosts: localhost
  vars:
    cleanup: 1
    appname: pgscv-distribution
  vars_files:
    - ./vars/{{ env }}.yml
  tasks:
    - name: Versioning | Register release tag
      command: git describe --tags --abbrev=0
      register: tag

    - name: Facts | Set fact about deployed application
      set_fact:
        app_version: "{{ tag.stdout }}"
        tmpdir: "/tmp/{{ appname }}-{{ env }}-{{ tag.stdout }}"

    - name: Paths | Create manifests temp directory
      file:
        path: "{{ tmpdir }}"
        state: directory

    - name: Manifests | Create deployment template
      template:
        src: templates/deployment.yml.j2
        dest: "{{ tmpdir }}/deployment.yml"

    - name: "Release | Deploy {{ appname }}"
      command: "kubectl apply -f {{ tmpdir }}/deployment.yml"

    - name: Paths | Remove manifests temp directory
      file:
        path: "{{ tmpdir }}"
        state: absent
      when: cleanup == 1
