---
name: Beta

on:
  workflow_dispatch:
  push:
    branches:
      - beta/*
      - dev/*

jobs:
  test:
    runs-on: ubuntu-22.04
    container: cherts/pgscv-test-runner:1.0.10
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run test
        run: make test

  build-beta:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Build beta image
        run: make docker-build-beta
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push beta image to Docker Hub
        run: make docker-push-beta
