---
name: Beta

on:
  workflow_dispatch:
  pull_request:
    types: [assigned, unassigned]
    paths:
      - "cmd/**"
      - "internal/**"
      - "discovery/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"

permissions:
  contents: write      # Required to create the GitHub Release
  id-token: write      # Required for Cosign keyless signing
  packages: write      # Required if pushing signed Docker images to GHCR
  attestations: write  # Required if pushing artifact attestation

jobs:
  test:
    name: ${{ matrix.task.name }} ${{ matrix.os.name }} ${{ matrix.postgres.name }} ${{ matrix.pgbouncer.name }}
    runs-on: ${{ matrix.os.runs-on }}
    container: ${{ matrix.os.container[matrix.postgres.postgres] }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
            matrix: linux
            container:
              15: docker://postgres:15
              16: docker://postgres:16
              17: docker://postgres:17
              18: docker://postgres:18
#          - name: Windows
#            runs-on: windows-latest
#            matrix: windows
#          - name: macOS
#            runs-on: macos-latest
#            matrix: macos
        pgbouncer:
          - name: PgBouncer v1.25
            pgbouncer: 1.25.2
          - name: PgBouncer v1.18
            pgbouncer: 1.18.0
          - name: PgBouncer v1.16
            pgbouncer: 1.16.1
          - name: PgBouncer v1.15
            pgbouncer: 1.15.0
        postgres:
          - name: PostgreSQL v15
            postgres: 15
            golang: 1.26.5
            revive: 1.15.0
            gosec: 2.28.0
          - name: PostgreSQL v16
            postgres: 16
            golang: 1.26.5
            revive: 1.15.0
            gosec: 2.28.0
          - name: PostgreSQL v17
            postgres: 17
            golang: 1.26.5
            revive: 1.15.0
            gosec: 2.28.0
          - name: PostgreSQL v18
            postgres: 18
            golang: 1.26.5
            revive: 1.15.0
            gosec: 2.28.0
    steps:
      - name: Set up pgbouncer ${{ matrix.pgbouncer.pgbouncer }}
        if: matrix.os.matrix == 'linux'
        run: |
          apt-get update
          apt-get -y upgrade
          echo "Set up pgbouncer ${{ matrix.pgbouncer.pgbouncer }}"
          apt-get install build-essential jq wget vim make gcc git curl libevent-dev libssl-dev pkg-config python3 pandoc -y
          wget https://www.pgbouncer.org/downloads/files/${{ matrix.pgbouncer.pgbouncer }}/pgbouncer-${{ matrix.pgbouncer.pgbouncer }}.tar.gz
          tar xzf pgbouncer-${{ matrix.pgbouncer.pgbouncer }}.tar.gz
          cd pgbouncer-${{ matrix.pgbouncer.pgbouncer }}
          ./configure --prefix=/usr/local
          make
          mkdir /etc/pgbouncer /var/log/pgbouncer /var/run/pgbouncer
          chown -R postgres:postgres /etc/pgbouncer /var/log/pgbouncer /var/run/pgbouncer
          cp pgbouncer /usr/sbin
          cp etc/pgbouncer.ini /etc/pgbouncer
          cp etc/pgbouncer.ini /etc/pgbouncer/pgbouncer.orig.ini
          export PATH=$PATH:/usr/local/bin:/usr/local/go/bin
          cd ..
          rm -f pgbouncer-${{ matrix.pgbouncer.pgbouncer }}.tar.gz
          rm -rf pgbouncer-${{ matrix.pgbouncer.pgbouncer }}
      - name: Set up golang ${{ matrix.postgres.golang }}
        if: matrix.os.matrix == 'linux'
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.postgres.golang }}
      - name: Set up revive ${{ matrix.postgres.revive }}
        if: matrix.os.matrix == 'linux'
        run: |
          curl -s -L https://github.com/mgechev/revive/releases/download/v${{ matrix.postgres.revive }}/revive_linux_amd64.tar.gz | tar xzf - -C $(go env GOROOT)/bin revive
      - name: Set up gosec ${{ matrix.postgres.gosec }}
        if: matrix.os.matrix == 'linux'
        run: |
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOROOT)/bin v${{ matrix.postgres.gosec }}
      - name: Prepare testing environment
        if: matrix.os.matrix == 'linux'
        run: |
          mkdir /opt/testing
          chmod 755 /opt/testing
          rm -rf /var/lib/apt/lists/*
      - name: Show versions
        run: |
          go version
          pgbouncer --version
          postgres --version
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Copy test environment script
        if: matrix.os.matrix == 'linux'
        run: |
          cp testing/prepare_test_environment.sh /opt/testing/
          cp testing/fixtures.sql /opt/testing/
      - name: Prepare PostgreSQL ${{ matrix.postgres.postgres }} and PgBouncer ${{ matrix.pgbouncer.pgbouncer }}
        run: |
          /opt/testing/prepare_test_environment.sh ${{ matrix.postgres.postgres }}
      - name: Set Git config
        run: git config --global --add safe.directory /__w/pgscv/pgscv
      - name: Check code modernization
        run: make modernize-check
      - name: Check code govulncheck
        run: make govulncheck
      - name: Run tests
        run: make test

  docker:
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set environment
        id: version
        run: |
          echo VERSION="0.15" >>$GITHUB_OUTPUT
          echo GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >>$GITHUB_OUTPUT
          echo GIT_COMMIT="$(git rev-parse --short "${GITHUB_SHA}")" >>$GITHUB_OUTPUT
          echo GIT_DATE="$(git log -1 --format=%cd --date=format:"%Y%m%d")" >>$GITHUB_OUTPUT
      - name: Set DockerHub environment
        id: dockerhub
        run: |
          echo DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" >>$GITHUB_OUTPUT
          echo DOCKERHUB_TOKEN="${{ secrets.DOCKERHUB_TOKEN }}" >>$GITHUB_OUTPUT
      - name: Set up Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/${{ github.repository }}
            cherts/pgscv
          tags: |
            type=raw,value=v${{ steps.version.outputs.VERSION }}-${{ steps.version.outputs.GIT_BRANCH }}-${{ steps.version.outputs.GIT_COMMIT }}-${{ steps.version.outputs.GIT_DATE }}-beta
      - name: Set up Cosign
        uses: sigstore/cosign-installer@v4.1.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to GHCR registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub registry
        if: ${{ steps.dockerhub.outputs.DOCKERHUB_USERNAME != '' && steps.dockerhub.outputs.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v4.6.0
        with:
          username: ${{ steps.dockerhub.outputs.DOCKERHUB_USERNAME }}
          password: ${{ steps.dockerhub.outputs.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: ${{ steps.dockerhub.outputs.DOCKERHUB_USERNAME != '' && steps.dockerhub.outputs.DOCKERHUB_TOKEN != '' }}
        id: build-and-push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.beta
          platforms: linux/386,linux/amd64,linux/arm,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=pgSCV is a PostgreSQL ecosystem metrics collector
      - name: Sign image with a cosign
        if: ${{ steps.dockerhub.outputs.DOCKERHUB_USERNAME != '' && steps.dockerhub.outputs.DOCKERHUB_TOKEN != '' }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
      - name: Cleanup registry
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: 'pgscv'
          package-type: container
          min-versions-to-keep: 10
#          delete-only-untagged-versions: 'true'

  goreleaser:
    runs-on: ubuntu-24.04
    needs: docker
    steps:
      - name: Run checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Set up Cosign
        uses: sigstore/cosign-installer@v4.1.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: release --snapshot --clean --skip=publish --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}