---
name: Default

on:
  push:
    paths:
      - "cmd/**"
      - "internal/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "cmd/**"
      - "internal/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    runs-on: ubuntu-latest
    container: cherts/pgscv-test-runner:1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test

