---
name: Release

on:
  push:
    tags: [ v* ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: barcodepro/weaponry-pgscv-test-runner:v0.0.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        env: [ staging, production ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: make docker-build -e ENV=${{ matrix.env }}
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
      - name: Push image to Docker Hub
        run: make docker-push -e ENV=${{ matrix.env }}
