---
name: Default

on:
  push:
    branches:
     - 'dev'
    paths-ignore:
      - ".github/**"
      - "deploy/**"
      - "testing/**"
      - "README*"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Launch reason'
        required: true
        default: 'Run tests'

jobs:
  test:
    runs-on: ubuntu-latest
    container: cherts/pgscv-test-runner:1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test
