---
name: Default

on:
  push:
    paths:
      - "cmd/**"
      - "internal/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "cmd/**"
      - "internal/**"
      - "Makefile"
      - "go.mod"
      - "go.sum"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: make docker-build-branch


jobs:
  test:
    runs-on: ubuntu-latest
    container: cherts/pgscv-test-runner:1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test
