---
name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: barcodepro/weaponry-pgscv-test-runner:v0.0.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test

  build_staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: make docker-build -e ENV=staging
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
      - name: Push image to Docker Hub
        run: make docker-push -e ENV=staging

  deploy_staging:
    runs-on: [self-hosted, staging]
    container: barcodepro/ansible:2.9.5-alpine
    needs: [ test, build_staging ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy on staging
        env:
          KUBECONFIG: /root/.kubeconfig
          KUBECONFIG_DATA: ${{ secrets.STAGING_KUBECONFIG_DATA }}
        run: |
          echo "$KUBECONFIG_DATA" > /root/.kubeconfig
          chmod 600 /root/.kubeconfig
          make deploy -e ENV=staging
