# __release_tag__ golang 1.13 was released 2019-09-03
# __release_tag__ golangci-lint v1.27.0 was released 2020-05-13
---
name: Default

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: barcodepro/weaponry-pgscv-test-runner:v0.0.1

    steps:
      - name: Set up golangci-lint
        run: |
          curl -s -L https://github.com/golangci/golangci-lint/releases/download/v1.27.0/golangci-lint-1.27.0-linux-amd64.tar.gz -o golangci-lint-1.27.0-linux-amd64.tar.gz
          tar xvzf golangci-lint-1.27.0-linux-amd64.tar.gz
          mv golangci-lint-1.27.0-linux-amd64/golangci-lint /usr/local/bin
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test
      - name: Race detector
        run: make race

#  build_staging:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Build image
#        run: make docker-build -e ENV=staging
#      - name: Log in to Docker Hub
#        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
#      - name: Push image to Docker Hub
#        run: make docker-push -e ENV=staging
#
#  deploy_staging:
#    runs-on: [self-hosted, staging]
#    container: barcodepro/ansible:2.9.5-alpine
#    needs: [ test, build ]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Deploy on staging
#        env:
#          KUBECONFIG: /root/.kubeconfig
#          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
#        run: |
#          echo "$KUBECONFIG_DATA" > /root/.kubeconfig
#          chmod 600 /root/.kubeconfig
#          make deploy -e ENV=staging
