---
name: Release

on:
  push:
    branches: [ release ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: weaponry/pgscv-test-runner:v0.0.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test

  deploy_production:
    runs-on: [self-hosted, production]
    container: weaponry/ansible:2.9.5-alpine
    needs: [ test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy on production
        env:
          KUBECONFIG: /root/.kubeconfig
          KUBECONFIG_DATA: ${{ secrets.PRODUCTION_KUBECONFIG_DATA }}
        run: |
          echo "$KUBECONFIG_DATA" > /root/.kubeconfig
          chmod 600 /root/.kubeconfig
          make deploy -e ENV=production
