---
name: Release

on:
  push:
    branches: [ release ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: barcodepro/weaponry-pgscv-test-runner:v0.0.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare test environment
        run: prepare-test-environment.sh
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test

  deploy_production:
    runs-on: [self-hosted, production]
    container: barcodepro/ansible:2.9.5-alpine
    needs: [ test, build_production ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy on staging
        env:
          KUBECONFIG: /root/.kubeconfig
          KUBECONFIG_DATA: ${{ secrets.PRODUCTION_KUBECONFIG_DATA }}
        run: |
          echo "$KUBECONFIG_DATA" > /root/.kubeconfig
          chmod 600 /root/.kubeconfig
          make deploy -e ENV=production
