name: "Reusable Workflow"
  
on:
  workflow_call: 

jobs:
  reusable_job:
    name: "Login into Docker Hub"
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}